name: Nginx CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the version as needed

      - name: Install dependencies
        run: npm install

      # - name: Test SSH Connection
      #   run: |
      #     ssh -i ~/.ssh/id_ed25519_GHActions root@mohammadzafar.com 'echo "SSH connection successful"'
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GH_SSH_PRIV_KEY }}

      # - name: Build
      #   run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        run: |
          ssh root@mohammadzafar.com 'cd /Venena && git pull && npm install && nohup npm start > /dev/null 2>&1 &'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
